version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: eladder-api-dev
    env_file: config.env
    volumes:
      - ./:/usr/src/api
    ports:
      - 3000:3000
      - 9222:9222
    command: yarn run serve-dev
    links:
      - db:db
  db:
    build:
      context: ./db
    env_file: config.env
    image: eladder-db-dev
    ports:
      - 5431:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
